language: objective-c
before_install:
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
    - brew update
    - brew unlink xctool
    - brew install xctool
    - sudo easy_install cpp-coveralls
    - sudo easy_install PyYAML
script: 
    - xctool -project HHUIImageNamed.xcodeproj -scheme HHUIImageNamed -sdk iphonesimulator build test ARCHS=i386 VALID_ARCHS=i386 ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
    - ./coveralls.rb --extension m -e HHUIImageNamed -e HHUIImageNamedTests
